### ISSUE TITLE
Date format error

### ISSUE THREAD

**Issue by meaz** [hubot-scripts/hubot-tell#9]
Here is what my bot answers:
`david: mike said at 2019-08-15T16:53:14.622Z: this is a test`

would be better to display like this:
`david: mike said at 2019-08-15 16:53 : this is a test`

or even:
`david: mike said on 2019-08-15 at 16:53 : this is a test`

**Comment by lorenzhs** [comment]
We use `Date.toLocaleString()` (see https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date/toLocaleString), so this looks like an issue with your locale. In addition, relative timestamps are optionally supported using the `timeago` package.
